version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: yourpassword
      DB_NAME: yourdb

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend


